version: "3"

services:

  runtime-setup:
    image: swift-linux-backtrace:22.04-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-jammy"

  test:
    image: swift-linux-backtrace:22.04-5.9
    environment:
      - FORCE_TEST_DISCOVERY=--enable-test-discovery

  shell:
    image: swift-linux-backtrace:22.04-5.9
