//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftLinuxBacktrace open source project
//
// Copyright (c) 2019-2020 Apple Inc. and the SwiftLinuxBacktrace project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftLinuxBacktrace project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// BacktraceTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension BacktraceTests {
    public static var allTests: [(String, (BacktraceTests) -> () throws -> Void)] {
        return [
            ("testFatalError", testFatalError),
            ("testSIGILL", testSIGILL),
            ("testSIGSEGV", testSIGSEGV),
            ("testSIGBUS", testSIGBUS),
            ("testSIGFPE", testSIGFPE),
        ]
    }
}
