//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftLinuxBacktrace open source project
//
// Copyright (c) 2019-2020 Apple Inc. and the SwiftLinuxBacktrace project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftLinuxBacktrace project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// FormatsTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension FormatsTests {
    public static var allTests: [(String, (FormatsTests) -> () throws -> Void)] {
        return [
            ("testFullFormat", testFullFormat),
            ("testFullFormatNoFunction", testFullFormatNoFunction),
            ("testFullFormatNoFile", testFullFormatNoFile),
            ("testFullFormatNoFileNoFunction", testFullFormatNoFileNoFunction),
            ("testColoredFormat", testColoredFormat),
            ("testColoredFormatNoFunction", testColoredFormatNoFunction),
            ("testColoredFormatNoFile", testColoredFormatNoFile),
            ("testColoredFormatNoFileNoFunction", testColoredFormatNoFileNoFunction),
        ]
    }
}
